"use strict";
// Stage "stages" — executed-JS extraction of the six VS stages' geometry
// (polygon / ground / platform / ceiling / walls / ledges / blastzone /
// spawns / scale / offset / connected / movingPlats) into generated C
// tables (fix_plan §M1 task 3; format STAB1, pipeline/FORMATS.md §4).
//
// EXECUTED-JS principle: walks the live stages/vs-stages registry out of
// the extractor bundle (built by pipeline/extractor/build-extractor.sh
// with upstream's own docker node:8 webpack toolchain) and serializes
// doubles as IEEE-754 uint64 bit patterns — exact by construction, never
// decimal round-trips (PLAN §2). Geometry is upstream's ONE source of
// truth for both collision (physics.js) and stage art (stagerender.js).

const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");
const { sha256, sha256File, stableStringify } = require("../lib/manifest");
const S = require("../lib/stages-schema");

const REPO_ROOT = path.join(__dirname, "..", "..");

function emitHeader(model, provenance) {
  const L = [];
  L.push("/* ml_stages.h — GENERATED VS-stage geometry tables (format STAB1 v" +
    model.formatVersion + "). DO NOT EDIT.");
  L.push(" *");
  L.push(" * Generated by pipeline/stages/stages.js from EXECUTED upstream JS");
  L.push(" * (schmooblidon/meleelight, pin " + provenance.upstreamHead + ")");
  L.push(" * via the extractor bundle dist/js/extractor.js");
  L.push(" * (sha256 " + provenance.extractorSha256 + ").");
  L.push(" *");
  L.push(" * Doubles are stored as IEEE-754 uint64 bit patterns (exact by");
  L.push(" * construction; adjacent decimal comments are human-readable");
  L.push(" * shortest-round-trip only). Decode with ml_stage_f64() (named");
  L.push(" * apart from ml_tables.h's ml_f64 so both headers can share a");
  L.push(" * TU). Spec: pipeline/FORMATS.md section 4. On disagreement");
  L.push(" * between code and spec, the spec + regenerated artifacts win.");
  L.push(" */");
  L.push("#ifndef ML_STAGES_H");
  L.push("#define ML_STAGES_H");
  L.push("");
  L.push("#include <stdint.h>");
  L.push("#include <string.h>");
  L.push("");
  L.push("#define ML_STAGES_FORMAT_VERSION " + model.formatVersion);
  L.push("#define ML_STAGE_COUNT 6 /* 0 battlefield, 1 ystory, 2 pstadium,");
  L.push("                            3 dreamland, 4 fdest, 5 fountain");
  L.push("                            == oracle harness --stage ids */");
  L.push("#define ML_STAGE_PLAYERS 4 /* spawn/respawn slots per stage */");
  L.push("");
  L.push("/* Reconstruct a double from its stored IEEE-754 bit pattern. */");
  L.push("static inline double ml_stage_f64(uint64_t bits) {");
  L.push("  double d;");
  L.push("  memcpy(&d, &bits, 8);");
  L.push("  return d;");
  L.push("}");
  L.push("");
  L.push("typedef struct { uint64_t x, y; } ml_stage_vec2b_t; /* double bits */");
  L.push("");
  L.push("/* Collision/render segment [p1 -> p2] (upstream Surface; the");
  L.push(" * optional SurfaceProperties third element does not exist on any");
  L.push(" * VS stage at the pin — its appearance is a format bump). */");
  L.push("typedef struct { uint64_t x1, y1, x2, y2; } ml_stage_surface_t;");
  L.push("");
  L.push("/* Ledge: type 0 = ground, 1 = platform; index into that surface");
  L.push(" * list; side 0 = left, 1 = right. ml_stage_t.ledge[i] pairs with");
  L.push(" * ledgePos[i]. */");
  L.push("typedef struct { int32_t type, index, side; } ml_stage_ledge_t;");
  L.push("");
  L.push("/* Connected-surface label (upstream getSurfaceFromStage enum):");
  L.push(" * type 0 g(round), 1 p(latform), 2 c(eiling), 3 wallL, 4 wallR.");
  L.push(" * present == 0 -> no connection on that side. */");
  L.push("typedef struct { uint8_t present; int32_t type, index; } ml_stage_conn_label_t;");
  L.push("typedef struct { ml_stage_conn_label_t l, r; } ml_stage_conn_t;");
  L.push("");
  L.push("typedef struct {");
  L.push("  const char *name;");
  L.push("  /* stage art + collision rings (model space, y up-negative at");
  L.push("   * draw; verbatim upstream polygon) */");
  L.push("  int32_t polygonCount;");
  L.push("  const int32_t *polygonVertCounts;");
  L.push("  const ml_stage_vec2b_t *const *polygons;");
  for (const kind of S.SURF_KINDS) {
    L.push(`  int32_t ${kind}Count;`);
    L.push(`  const ml_stage_surface_t *${kind}; /* NULL when count 0 */`);
  }
  L.push("  int32_t ledgeCount; /* == ledgePos count (parallel arrays) */");
  L.push("  const ml_stage_ledge_t *ledge;");
  L.push("  const ml_stage_vec2b_t *ledgePos;");
  L.push("  ml_stage_vec2b_t startingPoint[ML_STAGE_PLAYERS];");
  L.push("  int32_t startingFace[ML_STAGE_PLAYERS]; /* 1 | -1 */");
  L.push("  ml_stage_vec2b_t respawnPoints[ML_STAGE_PLAYERS];");
  L.push("  int32_t respawnFace[ML_STAGE_PLAYERS]; /* 1 | -1 */");
  L.push("  uint64_t blastzone[4]; /* minX, minY, maxX, maxY double bits */");
  L.push("  uint64_t scale; /* double bits */");
  L.push("  int32_t offset[2]; /* screen pixel offset */");
  L.push("  uint8_t hasConnected;");
  L.push("  const ml_stage_conn_t *connectedGround;   /* groundCount when hasConnected */");
  L.push("  const ml_stage_conn_t *connectedPlatform; /* platformCount when hasConnected */");
  L.push("  int32_t movingPlatCount; /* movement LOGIC is M2 sim code */");
  L.push("  const int32_t *movingPlats; /* platform indices */");
  L.push("} ml_stage_t;");
  L.push("");
  L.push("extern const ml_stage_t ml_stages[ML_STAGE_COUNT];");
  L.push("");
  L.push("#endif /* ML_STAGES_H */");
  return L.join("\n") + "\n";
}

function emitSource(model, provenance, tally) {
  const L = [];
  L.push("/* ml_stages.c — GENERATED VS-stage geometry tables (format STAB1 v" +
    model.formatVersion + "). DO NOT EDIT.");
  L.push(" * Provenance: upstream pin " + provenance.upstreamHead);
  L.push(" * extractor bundle sha256 " + provenance.extractorSha256);
  L.push(" * See ml_stages.h / pipeline/FORMATS.md section 4.");
  L.push(" */");
  L.push('#include "ml_stages.h"');
  L.push("");

  const f64 = (fv) => { tally.f64++; return `UINT64_C(0x${fv.bits}) /* ${fv.dec} */`; };
  const i32 = (v) => { tally.i32++; return String(v); };
  const vec = (p) => `{${f64(p.x)}, ${f64(p.y)}}`;

  for (const st of model.stages) {
    const id = st.stageId;
    L.push(`/* -- stage ${id}: ${st.name} -- */`);

    st.polygon.forEach((ring, r) => {
      L.push(`static const ml_stage_vec2b_t ml__stg_poly_${id}_${r}[] = {`);
      for (const p of ring) L.push(`  ${vec(p)},`);
      L.push("};");
    });
    if (st.polygon.length > 0) {
      L.push(`static const int32_t ml__stg_polyvc_${id}[] = {` +
        st.polygon.map((ring) => i32(ring.length)).join(", ") + "};");
      L.push(`static const ml_stage_vec2b_t *const ml__stg_polys_${id}[] = {` +
        st.polygon.map((_, r) => `ml__stg_poly_${id}_${r}`).join(", ") + "};");
    }

    for (const kind of S.SURF_KINDS) {
      if (st[kind].length === 0) continue;
      L.push(`static const ml_stage_surface_t ml__stg_${kind}_${id}[] = {`);
      for (const s of st[kind]) {
        L.push(`  {${f64(s[0].x)}, ${f64(s[0].y)}, ${f64(s[1].x)}, ${f64(s[1].y)}},`);
      }
      L.push("};");
    }

    L.push(`static const ml_stage_ledge_t ml__stg_ledge_${id}[] = {`);
    for (const l of st.ledge) {
      L.push(`  {${i32(l.type)}, ${i32(l.index)}, ${i32(l.side)}},`);
    }
    L.push("};");
    L.push(`static const ml_stage_vec2b_t ml__stg_ledgepos_${id}[] = {`);
    for (const p of st.ledgePos) L.push(`  ${vec(p)},`);
    L.push("};");

    if (st.connected) {
      [["g", "connectedGround"], ["p", "connectedPlatform"]].forEach(([tag], k) => {
        L.push(`static const ml_stage_conn_t ml__stg_conn_${tag}_${id}[] = {`);
        for (const pair of st.connected[k]) {
          const lab = (x) => x === null
            ? "{0, 0, 0}"
            : `{1, ${i32(x.type)}, ${i32(x.index)}}`;
          L.push(`  {${lab(pair[0])}, ${lab(pair[1])}},`);
        }
        L.push("};");
      });
    }

    if (st.movingPlats.length > 0) {
      L.push(`static const int32_t ml__stg_movplats_${id}[] = {` +
        st.movingPlats.map(i32).join(", ") + "};");
    }
    L.push("");
  }

  L.push("const ml_stage_t ml_stages[ML_STAGE_COUNT] = {");
  for (const st of model.stages) {
    const id = st.stageId;
    L.push(`  { /* ${id}: ${st.name} */`);
    L.push(`    "${st.name}",`);
    L.push(`    ${i32(st.polygon.length)}, ` +
      (st.polygon.length ? `ml__stg_polyvc_${id}, ml__stg_polys_${id},` : "NULL, NULL,"));
    for (const kind of S.SURF_KINDS) {
      L.push(`    ${i32(st[kind].length)}, ` +
        (st[kind].length ? `ml__stg_${kind}_${id},` : "NULL,"));
    }
    L.push(`    ${i32(st.ledge.length)}, ml__stg_ledge_${id}, ml__stg_ledgepos_${id},`);
    L.push("    {" + st.startingPoint.map(vec).join(", ") + "},");
    L.push("    {" + st.startingFace.map(i32).join(", ") + "},");
    L.push("    {" + st.respawnPoints.map(vec).join(", ") + "},");
    L.push("    {" + st.respawnFace.map(i32).join(", ") + "},");
    L.push("    {" + [st.blastzone.min.x, st.blastzone.min.y,
      st.blastzone.max.x, st.blastzone.max.y].map(f64).join(",\n     ") + "},");
    L.push(`    ${f64(st.scale)},`);
    L.push("    {" + st.offset.map(i32).join(", ") + "},");
    if (st.connected) {
      L.push(`    1, ml__stg_conn_g_${id}, ml__stg_conn_p_${id},`);
    } else {
      L.push("    0, NULL, NULL,");
    }
    L.push(`    ${i32(st.movingPlats.length)}, ` +
      (st.movingPlats.length ? `ml__stg_movplats_${id},` : "NULL,"));
    L.push("  },");
  }
  L.push("};");
  return L.join("\n") + "\n";
}

function run(ctx) {
  const { stages, srcSha256 } = S.loadStages(ctx.distRoot);
  const model = S.buildStageModel(stages);

  const upstreamHead = execFileSync("git",
    ["-C", ctx.distRoot, "rev-parse", "HEAD"], { encoding: "utf8" }).trim();
  const provenance = { upstreamHead, extractorSha256: srcSha256 };

  const tally = { f64: 0, i32: 0 };
  const artifacts = [];
  const write = (name, content) => {
    const buf = Buffer.from(content);
    fs.writeFileSync(path.join(ctx.outDir, name), buf);
    artifacts.push({ path: name, sha256: sha256(buf), bytes: buf.length });
    ctx.log(`  ${name}: ${buf.length} bytes`);
  };

  write("ml_stages.h", emitHeader(model, provenance));
  write("ml_stages.c", emitSource(model, provenance, tally));
  write("stages.json", stableStringify(model));

  // Coverage (exact executed counts; pinned in pipeline/expected.json).
  const cov = {
    stages: model.stages.length,
    polygonRings: 0, polygonVerts: 0,
    grounds: 0, platforms: 0, ceilings: 0, wallLs: 0, wallRs: 0,
    ledges: 0, connectedStages: 0, movingPlats: 0,
    f64Values: tally.f64, i32Values: tally.i32,
  };
  const perStage = {};
  for (const st of model.stages) {
    const ps = {
      polygonRings: st.polygon.length,
      polygonVerts: st.polygon.reduce((n, r) => n + r.length, 0),
      grounds: st.ground.length,
      platforms: st.platform.length,
      ceilings: st.ceiling.length,
      wallLs: st.wallL.length,
      wallRs: st.wallR.length,
      ledges: st.ledge.length,
      connected: st.connected ? 1 : 0,
      movingPlats: st.movingPlats.length,
    };
    for (const k of ["polygonRings", "polygonVerts", "grounds", "platforms",
      "ceilings", "wallLs", "wallRs", "ledges", "movingPlats"]) cov[k] += ps[k];
    cov.connectedStages += ps.connected;
    perStage[st.name] = ps;
  }

  artifacts.sort((a, b) => (a.path < b.path ? -1 : 1));
  return {
    format: "STAB1",
    sources: [
      { path: "dist/js/extractor.js", sha256: srcSha256 },
      { path: "pipeline/extractor/extractor.entry.js",
        sha256: sha256File(path.join(REPO_ROOT, "pipeline/extractor/extractor.entry.js")) },
      { path: "pipeline/extractor/extractor.config.js",
        sha256: sha256File(path.join(REPO_ROOT, "pipeline/extractor/extractor.config.js")) },
    ],
    coverage: cov,
    perStage,
    artifacts,
  };
}

module.exports = { name: "stages", run };
