"use strict";
// Stage "tables" — executed-JS extraction of the engine's character
// constants (attributes / framesData / intangibility / ECB / hitboxes)
// into generated C tables (fix_plan §M1 task 2; format CTAB1,
// pipeline/FORMATS.md §3).
//
// EXECUTED-JS principle: requires the extractor bundle built from the
// REAL upstream data modules by pipeline/extractor/build-extractor.sh
// (upstream's own docker node:8 webpack toolchain), walks the live
// registry objects, and serializes doubles as their IEEE-754 uint64 bit
// patterns — values are EXACT by construction, never decimal round-trips
// (PLAN §2). Nothing is hand-transcribed.

const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");
const { sha256, sha256File, stableStringify } = require("../lib/manifest");
const S = require("../lib/tables-schema");

const REPO_ROOT = path.join(__dirname, "..", "..");

function f64Lit(fv) {
  return `UINT64_C(0x${fv.bits}) /* ${fv.dec} */`;
}

function emitHeader(model, provenance) {
  const L = [];
  L.push("/* ml_tables.h — GENERATED engine tables (format CTAB1 v" +
    model.formatVersion + "). DO NOT EDIT.");
  L.push(" *");
  L.push(" * Generated by pipeline/stages/tables.js from EXECUTED upstream JS");
  L.push(" * (schmooblidon/meleelight, pin " + provenance.upstreamHead + ")");
  L.push(" * via the extractor bundle dist/js/extractor.js");
  L.push(" * (sha256 " + provenance.extractorSha256 + ").");
  L.push(" *");
  L.push(" * Doubles are stored as IEEE-754 uint64 bit patterns (exact by");
  L.push(" * construction; the adjacent comment decimal is human-readable");
  L.push(" * shortest-round-trip only). Decode with ml_f64(). Spec:");
  L.push(" * pipeline/FORMATS.md section 3. On disagreement between code and");
  L.push(" * spec, the spec + a regenerated artifact set win.");
  L.push(" */");
  L.push("#ifndef ML_TABLES_H");
  L.push("#define ML_TABLES_H");
  L.push("");
  L.push("#include <stdint.h>");
  L.push("#include <string.h>");
  L.push("");
  L.push("#define ML_TABLES_FORMAT_VERSION " + model.formatVersion);
  L.push("#define ML_CHARS 5 /* 0 marth, 1 puff, 2 fox, 3 falco, 4 falcon */");
  L.push("");
  L.push("/* Reconstruct a double from its stored IEEE-754 bit pattern. */");
  L.push("static inline double ml_f64(uint64_t bits) {");
  L.push("  double d;");
  L.push("  memcpy(&d, &bits, 8);");
  L.push("  return d;");
  L.push("}");
  L.push("");
  L.push("/* X-macro field lists (pinned order == emission order == the");
  L.push(" * canonical dump order, FORMATS.md section 3.6). */");
  L.push("#define ML_ATTR_F64_FIELDS(X) \\");
  L.push("  " + S.ATTR_F64.map((f) => `X(${f})`).join(" \\\n  "));
  L.push("#define ML_ATTR_I32_FIELDS(X) \\");
  L.push("  " + S.ATTR_I32.map((f) => `X(${f})`).join(" \\\n  "));
  L.push("#define ML_ATTR_I32V_FIELDS(X) \\");
  L.push("  " + S.ATTR_I32V.map(([f, n]) => `X(${f}, ${n})`).join(" \\\n  "));
  L.push("#define ML_ATTR_BOOL_FIELDS(X) \\");
  L.push("  " + S.ATTR_BOOL.map((f) => `X(${f})`).join(" \\\n  "));
  L.push("#define ML_HB_F64_FIELDS(X) \\");
  L.push("  " + S.HB_F64.map((f) => `X(${f})`).join(" \\\n  "));
  L.push("#define ML_HB_I32_FIELDS(X) \\");
  L.push("  " + S.HB_I32.map((f) => `X(${f})`).join(" \\\n  "));
  L.push("");
  L.push("typedef struct {");
  for (const f of S.ATTR_F64) L.push(`  uint64_t ${f}; /* double bits */`);
  for (const f of S.ATTR_I32) L.push(`  int32_t ${f};`);
  for (const [f, n] of S.ATTR_I32V) L.push(`  int32_t ${f}[${n}];`);
  for (const f of S.ATTR_BOOL) L.push(`  uint8_t ${f}; /* boolean */`);
  L.push("} ml_attributes_t;");
  L.push("");
  L.push("typedef struct { const char *name; int32_t frames; } ml_frames_entry_t;");
  L.push("typedef struct { const char *name; int32_t start; int32_t length; } ml_intang_entry_t;");
  L.push("");
  L.push("/* ECB quad, upstream order [bottomOffsetY, halfWidthX, midY, topY]");
  L.push(" * (consumed by src/physics/physics.js:1097-1102). */");
  L.push("typedef struct { int16_t v[4]; } ml_ecb_frame_t;");
  L.push("typedef struct {");
  L.push("  const char *name;");
  L.push("  int32_t frameCount;");
  L.push("  const ml_ecb_frame_t *frames;");
  L.push("} ml_ecb_state_t;");
  L.push("");
  L.push("typedef struct { uint64_t x, y; } ml_vec2b_t; /* double bits */");
  L.push("typedef struct {");
  L.push("  const ml_vec2b_t *offset; /* offsetCount entries */");
  L.push("  int32_t offsetCount;");
  L.push("  uint8_t offsetIsArray; /* 0: single Vec2D upstream; 1: per-frame array */");
  L.push("  uint8_t throwextra;    /* boolean */");
  for (const f of S.HB_F64) L.push(`  uint64_t ${f}; /* double bits */`);
  L.push("  int32_t " + S.HB_I32.join(", ") + ";");
  L.push("} ml_hitbox_t;");
  L.push("typedef struct {");
  L.push("  const char *name;");
  L.push("  const ml_hitbox_t *id[4]; /* id0..id3; NULL = absent upstream */");
  L.push("} ml_hitbox_move_t;");
  L.push("");
  L.push("extern const char *const ml_char_names[ML_CHARS];");
  L.push("extern const ml_attributes_t ml_attributes[ML_CHARS];");
  L.push("extern const int32_t ml_frames_count[ML_CHARS];");
  L.push("extern const ml_frames_entry_t *const ml_frames_data[ML_CHARS];");
  L.push("extern const int32_t ml_intang_count[ML_CHARS];");
  L.push("extern const ml_intang_entry_t *const ml_intang_data[ML_CHARS];");
  L.push("extern const int32_t ml_ecb_state_count[ML_CHARS];");
  L.push("extern const ml_ecb_state_t *const ml_ecb_states[ML_CHARS];");
  L.push("extern const int32_t ml_hitbox_move_count[ML_CHARS];");
  L.push("extern const ml_hitbox_move_t *const ml_hitbox_moves[ML_CHARS];");
  L.push("");
  L.push("#endif /* ML_TABLES_H */");
  return L.join("\n") + "\n";
}

function emitSource(model, provenance, tally) {
  const L = [];
  L.push("/* ml_tables.c — GENERATED engine tables (format CTAB1 v" +
    model.formatVersion + "). DO NOT EDIT.");
  L.push(" * Provenance: upstream pin " + provenance.upstreamHead);
  L.push(" * extractor bundle sha256 " + provenance.extractorSha256);
  L.push(" * See ml_tables.h / pipeline/FORMATS.md section 3.");
  L.push(" */");
  L.push('#include "ml_tables.h"');
  L.push("");
  L.push('const char *const ml_char_names[ML_CHARS] = {' +
    S.CHAR_NAMES.map((n) => `"${n}"`).join(", ") + "};");
  L.push("");

  const f64 = (fv) => { tally.f64++; return f64Lit(fv); };
  const i32 = (v) => { tally.i32++; return String(v); };

  // -- attributes --
  L.push("const ml_attributes_t ml_attributes[ML_CHARS] = {");
  for (const c of model.chars) {
    L.push(`  { /* ${c.name} */`);
    for (const f of S.ATTR_F64) L.push(`    ${f64(c.attributes.f64[f])},`);
    for (const f of S.ATTR_I32) L.push(`    ${i32(c.attributes.i32[f])},`);
    for (const [f] of S.ATTR_I32V) {
      L.push(`    {${c.attributes.i32v[f].map(i32).join(", ")}},`);
    }
    L.push("    " + S.ATTR_BOOL.map((f) => c.attributes.bool[f]).join(", ") + ",");
    L.push("  },");
  }
  L.push("};");
  L.push("");

  // -- framesData --
  for (const c of model.chars) {
    L.push(`static const ml_frames_entry_t ml__frames_${c.charId}[] = { /* ${c.name} */`);
    for (const [s, n] of Object.entries(c.framesData)) {
      L.push(`  {"${s}", ${i32(n)}},`);
    }
    L.push("};");
  }
  L.push("const int32_t ml_frames_count[ML_CHARS] = {" +
    model.chars.map((c) => Object.keys(c.framesData).length).join(", ") + "};");
  L.push("const ml_frames_entry_t *const ml_frames_data[ML_CHARS] = {" +
    model.chars.map((c) => `ml__frames_${c.charId}`).join(", ") + "};");
  L.push("");

  // -- intangibility --
  for (const c of model.chars) {
    L.push(`static const ml_intang_entry_t ml__intang_${c.charId}[] = { /* ${c.name} */`);
    for (const [s, v] of Object.entries(c.intangibility)) {
      L.push(`  {"${s}", ${i32(v[0])}, ${i32(v[1])}},`);
    }
    L.push("};");
  }
  L.push("const int32_t ml_intang_count[ML_CHARS] = {" +
    model.chars.map((c) => Object.keys(c.intangibility).length).join(", ") + "};");
  L.push("const ml_intang_entry_t *const ml_intang_data[ML_CHARS] = {" +
    model.chars.map((c) => `ml__intang_${c.charId}`).join(", ") + "};");
  L.push("");

  // -- ecb --
  for (const c of model.chars) {
    const states = Object.entries(c.ecb);
    states.forEach(([s, frames], si) => {
      if (frames.length === 0) return; // verbatim-empty upstream: NULL below
      tally.i32 += frames.length * 4;
      L.push(`static const ml_ecb_frame_t ml__ecb_f_${c.charId}_${si}[] = /* ${c.name}/${s} */`);
      L.push("  {" + frames.map((fr) => `{{${fr.join(",")}}}`).join(",") + "};");
    });
    L.push(`static const ml_ecb_state_t ml__ecb_${c.charId}[] = { /* ${c.name} */`);
    states.forEach(([s, frames], si) => {
      const ptr = frames.length === 0 ? "NULL" : `ml__ecb_f_${c.charId}_${si}`;
      L.push(`  {"${s}", ${frames.length}, ${ptr}},`);
    });
    L.push("};");
  }
  L.push("const int32_t ml_ecb_state_count[ML_CHARS] = {" +
    model.chars.map((c) => Object.keys(c.ecb).length).join(", ") + "};");
  L.push("const ml_ecb_state_t *const ml_ecb_states[ML_CHARS] = {" +
    model.chars.map((c) => `ml__ecb_${c.charId}`).join(", ") + "};");
  L.push("");

  // -- hitboxes --
  for (const c of model.chars) {
    const moves = Object.entries(c.hitboxes);
    moves.forEach(([mv, move], mi) => {
      for (const idk of ["id0", "id1", "id2", "id3"]) {
        const hb = move[idk];
        if (!hb) continue;
        const sym = `${c.charId}_${mi}_${idk.slice(2)}`;
        L.push(`static const ml_vec2b_t ml__hb_off_${sym}[] = { /* ${c.name}/${mv}/${idk} */`);
        for (const p of hb.offset) {
          L.push(`  {${f64(p.x)}, ${f64(p.y)}},`);
        }
        L.push("};");
        L.push(`static const ml_hitbox_t ml__hb_${sym} = {`);
        L.push(`  ml__hb_off_${sym}, ${hb.offset.length}, ${hb.offsetIsArray}, ${hb.throwextra},`);
        L.push("  " + S.HB_F64.map((f) => f64(hb[f])).join(", ") + ",");
        L.push("  " + S.HB_I32.map((f) => i32(hb[f])).join(", "));
        L.push("};");
      }
    });
    L.push(`static const ml_hitbox_move_t ml__hb_moves_${c.charId}[] = { /* ${c.name} */`);
    moves.forEach(([mv, move], mi) => {
      const ids = ["id0", "id1", "id2", "id3"].map((idk) =>
        move[idk] ? `&ml__hb_${c.charId}_${mi}_${idk.slice(2)}` : "NULL");
      L.push(`  {"${mv}", {${ids.join(", ")}}},`);
    });
    L.push("};");
  }
  L.push("const int32_t ml_hitbox_move_count[ML_CHARS] = {" +
    model.chars.map((c) => Object.keys(c.hitboxes).length).join(", ") + "};");
  L.push("const ml_hitbox_move_t *const ml_hitbox_moves[ML_CHARS] = {" +
    model.chars.map((c) => `ml__hb_moves_${c.charId}`).join(", ") + "};");
  return L.join("\n") + "\n";
}

function run(ctx) {
  const { tables, srcSha256 } = S.loadTables(ctx.distRoot);
  const model = S.buildModel(tables);

  const upstreamHead = execFileSync("git",
    ["-C", ctx.distRoot, "rev-parse", "HEAD"], { encoding: "utf8" }).trim();
  const provenance = { upstreamHead, extractorSha256: srcSha256 };

  const tally = { f64: 0, i32: 0 };
  const artifacts = [];
  const write = (name, content) => {
    const buf = Buffer.from(content);
    fs.writeFileSync(path.join(ctx.outDir, name), buf);
    artifacts.push({ path: name, sha256: sha256(buf), bytes: buf.length });
    ctx.log(`  ${name}: ${buf.length} bytes`);
  };

  write("ml_tables.h", emitHeader(model, provenance));
  write("ml_tables.c", emitSource(model, provenance, tally));
  write("tables.json", stableStringify(model));

  // Coverage (exact executed counts; pinned in pipeline/expected.json).
  const cov = {
    chars: model.chars.length,
    attrFields: S.ATTR_F64.length + S.ATTR_I32.length + S.ATTR_I32V.length +
      S.ATTR_BOOL.length,
    framesStates: 0, intangStates: 0,
    ecbStates: 0, ecbFrames: 0, ecbEmptyStates: 0,
    hitboxMoves: 0, hitboxes: 0, hitboxOffsetVecs: 0,
    f64Values: tally.f64, i32Values: tally.i32,
  };
  const perChar = {};
  for (const c of model.chars) {
    const pc = {
      framesStates: Object.keys(c.framesData).length,
      intangStates: Object.keys(c.intangibility).length,
      ecbStates: Object.keys(c.ecb).length,
      ecbFrames: Object.values(c.ecb).reduce((n, f) => n + f.length, 0),
      ecbEmptyStates: Object.values(c.ecb).filter((f) => f.length === 0).length,
      hitboxMoves: Object.keys(c.hitboxes).length,
      hitboxes: 0, hitboxOffsetVecs: 0,
    };
    for (const move of Object.values(c.hitboxes)) {
      for (const hb of Object.values(move)) {
        pc.hitboxes++;
        pc.hitboxOffsetVecs += hb.offset.length;
      }
    }
    for (const k of ["framesStates", "intangStates", "ecbStates", "ecbFrames",
      "ecbEmptyStates", "hitboxMoves", "hitboxes", "hitboxOffsetVecs"]) cov[k] += pc[k];
    perChar[c.name] = pc;
  }

  artifacts.sort((a, b) => (a.path < b.path ? -1 : 1));
  return {
    format: "CTAB1",
    sources: [
      { path: "dist/js/extractor.js", sha256: srcSha256 },
      { path: "pipeline/extractor/extractor.entry.js",
        sha256: sha256File(path.join(REPO_ROOT, "pipeline/extractor/extractor.entry.js")) },
      { path: "pipeline/extractor/extractor.config.js",
        sha256: sha256File(path.join(REPO_ROOT, "pipeline/extractor/extractor.config.js")) },
    ],
    coverage: cov,
    perChar,
    artifacts,
  };
}

module.exports = { name: "tables", run };
