"use strict";
// Stage "targets" — executed-JS extraction of the ten AUTHORED
// target-test stages (box / target / ground / platform / ceiling /
// walls / ledges / blastzone / startingPoint / scale / offset) into
// generated C tables (fix_plan §M4 task 11; format TTAB1,
// pipeline/FORMATS.md §6).
//
// EXECUTED-JS principle: walks the live stages/targetstages/tstages
// registry out of the extractor bundle (built by
// pipeline/extractor/build-extractor.sh with upstream's own docker
// node:8 webpack toolchain) and serializes doubles as IEEE-754 uint64
// bit patterns — exact by construction, never decimal round-trips
// (PLAN §2). One-source-of-truth: upstream renders target stages from
// the SAME structures physics + targetplay collide against
// (stagerender.js box/surfaces; targetplay.js target[] radius size+7).

const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");
const { sha256, sha256File, stableStringify } = require("../lib/manifest");
const T = require("../lib/targets-schema");

const REPO_ROOT = path.join(__dirname, "..", "..");

function emitHeader(model, provenance) {
  const L = [];
  L.push("/* ml_targets.h — GENERATED target-test stage tables (format TTAB1 v" +
    model.formatVersion + "). DO NOT EDIT.");
  L.push(" *");
  L.push(" * Generated by pipeline/stages/targets.js from EXECUTED upstream JS");
  L.push(" * (schmooblidon/meleelight, pin " + provenance.upstreamHead + ")");
  L.push(" * via the extractor bundle dist/js/extractor.js");
  L.push(" * (sha256 " + provenance.extractorSha256 + ").");
  L.push(" *");
  L.push(" * Doubles are stored as IEEE-754 uint64 bit patterns (exact by");
  L.push(" * construction; adjacent decimal comments are human-readable");
  L.push(" * shortest-round-trip only). Decode with ml_target_f64() (named");
  L.push(" * apart from ml_stage_f64/ml_f64 so all headers can share a TU).");
  L.push(" * Spec: pipeline/FORMATS.md section 6. On disagreement between");
  L.push(" * code and spec, the spec + regenerated artifacts win.");
  L.push(" */");
  L.push("#ifndef ML_TARGETS_H");
  L.push("#define ML_TARGETS_H");
  L.push("");
  L.push("#include <stdint.h>");
  L.push("#include <string.h>");
  L.push("");
  L.push("#define ML_TARGETS_FORMAT_VERSION " + model.formatVersion);
  L.push("#define ML_TSTAGE_COUNT 10 /* 0..9 == upstream targetStageMapping");
  L.push("                              (activeStage.js) == the");
  L.push("                              setActiveStageTarget selection ids */");
  L.push("");
  L.push("/* Reconstruct a double from its stored IEEE-754 bit pattern. */");
  L.push("static inline double ml_target_f64(uint64_t bits) {");
  L.push("  double d;");
  L.push("  memcpy(&d, &bits, 8);");
  L.push("  return d;");
  L.push("}");
  L.push("");
  L.push("typedef struct { uint64_t x, y; } ml_tstage_vec2b_t; /* double bits */");
  L.push("");
  L.push("/* Collision/render segment [p1 -> p2] (upstream Surface; NO");
  L.push(" * authored stage carries the optional SurfaceProperties third");
  L.push(" * element — measured iter 94; its appearance is a format bump). */");
  L.push("typedef struct { uint64_t x1, y1, x2, y2; } ml_tstage_surface_t;");
  L.push("");
  L.push("/* Authored AABB (upstream Box2D {min,max}). */");
  L.push("typedef struct { uint64_t minX, minY, maxX, maxY; } ml_tstage_box_t;");
  L.push("");
  L.push("/* Ledge: type 0 = ground, 1 = platform; index into that surface");
  L.push(" * list; side 0 = left, 1 = right. ledgePos is OPTIONAL upstream:");
  L.push(" * exactly one authored stage (targetstage9) carries it (parallel");
  L.push(" * to ledge; AI-only upstream, carried verbatim). */");
  L.push("typedef struct { int32_t type, index, side; } ml_tstage_ledge_t;");
  L.push("");
  L.push("typedef struct {");
  L.push("  const char *name;");
  L.push("  ml_tstage_vec2b_t startingPoint; /* [0] — the only slot authored */");
  L.push("  int32_t boxCount;");
  L.push("  const ml_tstage_box_t *box; /* NULL when count 0 */");
  for (const kind of T.SURF_KINDS) {
    L.push(`  int32_t ${kind}Count;`);
    L.push(`  const ml_tstage_surface_t *${kind}; /* NULL when count 0 */`);
  }
  L.push("  int32_t ledgeCount;");
  L.push("  const ml_tstage_ledge_t *ledge; /* NULL when count 0 */");
  L.push("  uint8_t hasLedgePos;");
  L.push("  const ml_tstage_vec2b_t *ledgePos; /* ledgeCount entries when");
  L.push("                                        hasLedgePos, else NULL */");
  L.push("  int32_t targetCount; /* breakable targets (radius = CODE literal");
  L.push("                          7 in targetplay.js, not data) */");
  L.push("  const ml_tstage_vec2b_t *target;");
  L.push("  uint64_t scale; /* double bits */");
  L.push("  uint64_t blastzone[4]; /* minX, minY, maxX, maxY double bits */");
  L.push("  int32_t offset[2]; /* screen pixel offset */");
  L.push("} ml_tstage_t;");
  L.push("");
  L.push("extern const ml_tstage_t ml_tstages[ML_TSTAGE_COUNT];");
  L.push("");
  L.push("#endif /* ML_TARGETS_H */");
  return L.join("\n") + "\n";
}

function emitSource(model, provenance, tally) {
  const L = [];
  L.push("/* ml_targets.c — GENERATED target-test stage tables (format TTAB1 v" +
    model.formatVersion + "). DO NOT EDIT.");
  L.push(" * Provenance: upstream pin " + provenance.upstreamHead);
  L.push(" * extractor bundle sha256 " + provenance.extractorSha256);
  L.push(" * See ml_targets.h / pipeline/FORMATS.md section 6.");
  L.push(" */");
  L.push('#include "ml_targets.h"');
  L.push("");

  const f64 = (fv) => { tally.f64++; return `UINT64_C(0x${fv.bits}) /* ${fv.dec} */`; };
  const i32 = (v) => { tally.i32++; return String(v); };
  const vec = (p) => `{${f64(p.x)}, ${f64(p.y)}}`;

  for (const st of model.stages) {
    const id = st.tstageId;
    L.push(`/* -- target stage ${id}: ${st.name} -- */`);

    if (st.box.length > 0) {
      L.push(`static const ml_tstage_box_t ml__tstg_box_${id}[] = {`);
      for (const b of st.box) {
        L.push(`  {${f64(b.min.x)}, ${f64(b.min.y)}, ${f64(b.max.x)}, ${f64(b.max.y)}},`);
      }
      L.push("};");
    }

    for (const kind of T.SURF_KINDS) {
      if (st[kind].length === 0) continue;
      L.push(`static const ml_tstage_surface_t ml__tstg_${kind}_${id}[] = {`);
      for (const s of st[kind]) {
        L.push(`  {${f64(s[0].x)}, ${f64(s[0].y)}, ${f64(s[1].x)}, ${f64(s[1].y)}},`);
      }
      L.push("};");
    }

    if (st.ledge.length > 0) {
      L.push(`static const ml_tstage_ledge_t ml__tstg_ledge_${id}[] = {`);
      for (const l of st.ledge) {
        L.push(`  {${i32(l.type)}, ${i32(l.index)}, ${i32(l.side)}},`);
      }
      L.push("};");
    }

    if (st.ledgePos) {
      L.push(`static const ml_tstage_vec2b_t ml__tstg_ledgepos_${id}[] = {`);
      for (const p of st.ledgePos) L.push(`  ${vec(p)},`);
      L.push("};");
    }

    L.push(`static const ml_tstage_vec2b_t ml__tstg_target_${id}[] = {`);
    for (const p of st.target) L.push(`  ${vec(p)},`);
    L.push("};");
    L.push("");
  }

  L.push("const ml_tstage_t ml_tstages[ML_TSTAGE_COUNT] = {");
  for (const st of model.stages) {
    const id = st.tstageId;
    L.push(`  { /* ${id}: ${st.name} */`);
    L.push(`    "${st.name}",`);
    L.push(`    ${vec(st.startingPoint[0])},`);
    L.push(`    ${i32(st.box.length)}, ` +
      (st.box.length ? `ml__tstg_box_${id},` : "NULL,"));
    for (const kind of T.SURF_KINDS) {
      L.push(`    ${i32(st[kind].length)}, ` +
        (st[kind].length ? `ml__tstg_${kind}_${id},` : "NULL,"));
    }
    L.push(`    ${i32(st.ledge.length)}, ` +
      (st.ledge.length ? `ml__tstg_ledge_${id},` : "NULL,"));
    L.push(st.ledgePos ? `    1, ml__tstg_ledgepos_${id},` : "    0, NULL,");
    L.push(`    ${i32(st.target.length)}, ml__tstg_target_${id},`);
    L.push(`    ${f64(st.scale)},`);
    L.push("    {" + [st.blastzone.min.x, st.blastzone.min.y,
      st.blastzone.max.x, st.blastzone.max.y].map(f64).join(",\n     ") + "},");
    L.push("    {" + st.offset.map(i32).join(", ") + "},");
    L.push("  },");
  }
  L.push("};");
  return L.join("\n") + "\n";
}

function run(ctx) {
  const { tstages, srcSha256 } = T.loadTargetStages(ctx.distRoot);
  const model = T.buildTargetStageModel(tstages);

  const upstreamHead = execFileSync("git",
    ["-C", ctx.distRoot, "rev-parse", "HEAD"], { encoding: "utf8" }).trim();
  const provenance = { upstreamHead, extractorSha256: srcSha256 };

  const tally = { f64: 0, i32: 0 };
  const artifacts = [];
  const write = (name, content) => {
    const buf = Buffer.from(content);
    fs.writeFileSync(path.join(ctx.outDir, name), buf);
    artifacts.push({ path: name, sha256: sha256(buf), bytes: buf.length });
    ctx.log(`  ${name}: ${buf.length} bytes`);
  };

  write("ml_targets.h", emitHeader(model, provenance));
  write("ml_targets.c", emitSource(model, provenance, tally));
  write("targets.json", stableStringify(model));

  // Coverage (exact executed counts; pinned in pipeline/expected.json).
  const cov = {
    stages: model.stages.length,
    boxes: 0, targets: 0,
    grounds: 0, platforms: 0, ceilings: 0, wallLs: 0, wallRs: 0,
    ledges: 0, ledgePosStages: 0,
    f64Values: tally.f64, i32Values: tally.i32,
  };
  const perStage = {};
  for (const st of model.stages) {
    const ps = {
      boxes: st.box.length,
      grounds: st.ground.length,
      platforms: st.platform.length,
      ceilings: st.ceiling.length,
      wallLs: st.wallL.length,
      wallRs: st.wallR.length,
      ledges: st.ledge.length,
      ledgePos: st.ledgePos ? 1 : 0,
      targets: st.target.length,
    };
    for (const k of ["boxes", "grounds", "platforms", "ceilings", "wallLs",
      "wallRs", "ledges", "targets"]) cov[k] += ps[k];
    cov.ledgePosStages += ps.ledgePos;
    perStage[st.name] = ps;
  }

  artifacts.sort((a, b) => (a.path < b.path ? -1 : 1));
  return {
    format: "TTAB1",
    sources: [
      { path: "dist/js/extractor.js", sha256: srcSha256 },
      { path: "pipeline/extractor/extractor.entry.js",
        sha256: sha256File(path.join(REPO_ROOT, "pipeline/extractor/extractor.entry.js")) },
      { path: "pipeline/extractor/extractor.config.js",
        sha256: sha256File(path.join(REPO_ROOT, "pipeline/extractor/extractor.config.js")) },
    ],
    coverage: cov,
    perStage,
    artifacts,
  };
}

module.exports = { name: "targets", run };
