#!/usr/bin/env bash
# record-snd.sh — record + freeze the s01 stop-path scenario golden into
# port/goldens-snd/ (M4 task 6; the record-m4.sh procedure with the
# goldens dir changed — see manifest.json's LOCATION NOTE for why this
# twin exists. oracle/harness bytes are reused VERBATIM BY PATH; the
# quality contract is port/goldens-m4/check-quality.js BY PATH;
# HARD RULE 3: oracle/ and port/goldens-m4/ are read-only here).
#
# Usage: bash port/goldens-snd/record-snd.sh <golden-id> [--refreeze]
#
# Procedure (params come ONLY from port/goldens-snd/manifest.json):
#   1. the golden's trace must exist (generated by its CRAFTED generator
#      `node port/goldens-snd/gen-s01-trace.js <trace>` — deterministic,
#      byte-reproducible; NOT gen-trace.js);
#   2. TWO fresh browser runs via the UNCHANGED oracle/harness/run.js;
#   3. oracle/harness/compare.js asserts the runs bit-identical;
#   4. port/goldens-m4/check-quality.js asserts the M0 gameplay-quality
#      contract on run A;
#   5. freeze-stream-snd.js writes port/goldens-snd/<name>.sha256.json
#      (M0-identical format);
#   6. verify-stream.js self-check: run A verifies against the frozen file.
set -euo pipefail
cd "$(dirname "$0")/../.."

ID="${1:?usage: bash port/goldens-snd/record-snd.sh <golden-id> [--refreeze]}"
REFREEZE=""
[ "${2:-}" = "--refreeze" ] && REFREEZE="--refreeze"

SNDG=port/goldens-snd
HARNESS=oracle/harness

DIST="${MELEELIGHT_CLONE:-$HOME/.cache/meleelight-funkey-s/upstream}"
if [ ! -f "$DIST/dist/meleelight.html" ]; then
  echo "record-snd.sh: no built upstream at $DIST — run oracle/build-upstream.sh" >&2
  exit 1
fi

# Pull the golden's params out of the manifest as shell assignments.
eval "$(node -e '
  const fs = require("fs");
  const m = JSON.parse(fs.readFileSync("port/goldens-snd/manifest.json", "utf8"));
  const g = m.goldens.find((x) => x.id === process.argv[1] || x.name === process.argv[1]);
  if (!g) { console.error("unknown snd golden: " + process.argv[1]); process.exit(1); }
  const sq = (s) => "'\''" + String(s) + "'\''";
  console.log("NAME=" + sq(g.name));
  console.log("TRACE=" + sq(g.trace));
  console.log("FRAMES=" + sq(g.frames));
  console.log("SEED=" + sq(g.seed));
  console.log("P1=" + sq(g.p1));
  console.log("P2=" + sq(g.p2));
  console.log("STAGE=" + sq(g.stage));
  console.log("CPU=" + sq(g.cpu));
  console.log("DIFFICULTY=" + sq(g.difficulty));
' "$ID")"

if [ ! -f "$SNDG/$TRACE" ]; then
  echo "record-snd.sh: generating the crafted scenario trace"
  node "$SNDG/gen-s01-trace.js" "$SNDG/$TRACE"
fi

REPO="$PWD"
RUN=(node run.js --dist "$DIST" --trace "$REPO/$SNDG/$TRACE"
     --frames "$FRAMES" --seed "$SEED"
     --p1 "$P1" --p2 "$P2" --stage "$STAGE")
if [ "$CPU" = "true" ]; then
  RUN+=(--cpu --difficulty "$DIFFICULTY")
fi

cd "$HARNESS"
echo "record-snd.sh: $NAME — fresh run A"
"${RUN[@]}" --out "out/record-$ID-a.json"
echo "record-snd.sh: $NAME — fresh run B"
"${RUN[@]}" --out "out/record-$ID-b.json"

echo "record-snd.sh: comparing the two fresh runs"
node compare.js "out/record-$ID-a.json" "out/record-$ID-b.json"
cd "$REPO"

echo "record-snd.sh: gameplay-quality contract (mechanical; BY PATH)"
node port/goldens-m4/check-quality.js "$HARNESS/out/record-$ID-a.json"

echo "record-snd.sh: freezing into $SNDG/"
node "$SNDG/freeze-stream-snd.js" "$ID" "$HARNESS/out/record-$ID-a.json" \
  "$HARNESS/out/record-$ID-b.json" $REFREEZE

echo "record-snd.sh: self-check — run A vs frozen stream (unchanged verifier)"
node "$HARNESS/verify-stream.js" "$HARNESS/out/record-$ID-a.json" \
  "$SNDG/$NAME.sha256.json"

echo "RECORDED $ID -> $SNDG/$NAME.sha256.json"
