// port/gfx/gfx_vfx.h — the vfx render plane + HUD overlay + background art
// (M4 task 2). Structure-parallel translation of:
//   - src/main/vfx/renderVfx.js + drawVfx.js + vfxQueue.js (the per-frame
//     vfx queue: timer++, per-name dVfx draw, pop when expired);
//   - src/main/vfx/dVfx/*.js (every draw fn; hitCurve is upstream's own
//     empty TODO and draws nothing);
//   - src/main/vfx/{stars,lines}.js + the in-draw drawVfx re-spawn sites
//     (burning/firehit -> fireburst/burncircle, laser -> laserSpark lines,
//     shine -> stars) — RENDER-plane spawns, never on the sim seam;
//   - src/main/render.js renderOverlay(true) (timer text, percent
//     displays, stock icons, lost-stock burst) — percentShake is the
//     CHECKSUM.md section-7 timing-dependent exclusion: C draws unshaken;
//   - src/main/vfx/dVfx/start.js (the Ready--Go! banner; text via the
//     browser-rasterized composite sprites in VFXGLYPHS1);
//   - src/stages/stagerender.js drawBackgroundInit/drawBackground
//     (bg1 gradient + starfield/mountains or tunnel) — bg layers are NOT
//     in the IoU mask on either side; the C compositor draws them with
//     rast_ink_enable(0) so device pixels get art without polluting the
//     ink plane.
//
// DATA: vfx templates (the post-alias vfx[name] object: authored path
// arrays, frames, colours) + swordSwings come from the EXECUTED VFXDATA1
// dump (capture-canvas.js --vfxdata; committed port/gfx/vfxdata-frozen.txt,
// cmp-tripwired) — never hand-typed (hard rule 5). Text glyphs/banner
// sprites come from the EXECUTED VFXGLYPHS1 atlas (browser-rasterized
// Arial at capture time, area-averaged down to device scale; committed
// port/gfx/vfxglyphs-frozen.txt).
//
// RNG: render-plane randomness (star scatter, tail jitter, lightning,
// entrance seeds, ...) draws from a render-LOCAL mulberry32 with a fixed
// seed — NEVER ml_random / the seeded gameplay chain (upstream uses the
// native Math.random here; the browser reference capture swaps native RNG
// in around its render call for the same reason). x2 C byte-stability
// holds because the local stream is deterministic.
//
// SPAWN SEAM: sim-plane spawns arrive through ml_vfx_sink at ENQUEUE time
// (ml_events.h; queues reset per tick stage). circleDust's 4 seeded draws
// are burned by ml_drawVfx_cfg exactly as before; their VALUES ride the
// event (MlVfx has_dust/dust) so the C circles match the browser
// bit-for-bit. Install the sink BEFORE sim_setup_match (the boot
// entrance/start events fire inside it).
#ifndef GFX_GFX_VFX_H
#define GFX_GFX_VFX_H

#include "gfx.h"
#include "../sim/ml_events.h"

// --- data planes ---------------------------------------------------------
void gfx_vfx_load(const char *vfxdataPath);   // VFXDATA1 (strict, loud)
void gfx_glyphs_load(const char *glyphsPath); // VFXGLYPHS1 (strict, loud)

// --- lifecycle -----------------------------------------------------------
// Reset queue + overlay + background + render-local RNG state and bind
// the Gfx the sink spawns into. Installs ml_vfx_sink. Call BEFORE
// sim_setup_match so the boot entrance/start events are captured.
void gfx_vfx_install(Gfx *g);

// C drawVfx (drawVfx.js): spawn one instance from a config. The sink
// target; also the injection entry point (check-render.sh synthetic
// coverage table, expected-render.json "inject").
void gfx_vfx_spawn(const MlVfx *cfg);

// Synthetic-injection table (INJECT1 grammar, generated by
// check-render.sh from expected-render.json). frame < 0 disables.
void gfx_vfx_inject_load(const char *path);
void gfx_vfx_inject_fire(long frame); // spawn table configs when frame matches

// --- per-frame passes (called by gfx_render_frame in order) ---------------
void gfx_render_background(Gfx *g);                        // ink-suppressed
void gfx_render_vfx(Gfx *g, const GameState *st);          // renderVfx()
void gfx_render_overlay(Gfx *g, const GameState *st);      // renderOverlay(true)
// renderOverlay(false) — the TIMER block only (the `!versusMode ||
// gameMode == 5` arm; render.js:392-411): target mode's HUD (M4 task
// 12). Extracted from gfx_render_overlay — the VS path calls the same
// bytes (behavioral identity; RENDER OK is the regression).
void gfx_render_overlay_timer(Gfx *g, const GameState *st);
// M4 task 12 (gfx_target.c consumes; visibility-only wrappers around
// gfx_render.c's static passes — bodies untouched):
void gfx_render_player_pass(Gfx *g, const GameState *st, int i);
void gfx_render_articles_pass(Gfx *g, const GameState *st);

// --- glyph atlas (gfx_overlay.c; VFXGLYPHS1) ------------------------------
// Fonts, in the exact upstream draw forms (renderOverlay/start.js):
typedef enum {
  GFX_FONT_T40 = 0, // "900 40px Arial", strokeText lineWidth 2 (timer MM:SS)
  GFX_FONT_T25 = 1, // "900 25px Arial", lineWidth 2 (timer centiseconds)
  GFX_FONT_P53 = 2, // "900 53px Arial" under scale(0.8,1), lw 2 (percents)
  GFX_FONT_C70 = 3, // "italic 700 70px Arial", lw 10 (Ready countdown)
  GFX_FONT_COUNT = 4
} GfxFontId;

// Draw text at a device-space pen (x = left edge of the first glyph's
// advance box, y = baseline). strokeFirst mirrors the upstream call order
// (timer/percents: fill then stroke; countdown: stroke then fill).
void gfx_glyph_text(Gfx *g, int fontId, const char *s, double penX,
                    double penY, RastCol fill, RastCol stroke, int strokeFirst);
double gfx_glyph_text_width(int fontId, const char *s); // device px

// Blit a composite banner sprite ("ready" / "go") anchored at the
// upstream fillText anchor (canvas px 240,420 / 240,470 -> device).
void gfx_sprite_blit(Gfx *g, const char *name, double anchorCanvasX,
                     double anchorCanvasY);

// module-state resets (called by gfx_vfx_install)
void gfx_overlay_reset(void);
void gfx_bg_reset(void);

// the live boxFill (stagerender.js module state: drawBackgroundInit
// baseline, mutated per frame by drawStars' hsla animation) — the stage
// polygon pass reads it (gfx_render.c).
RastCol gfx_bg_box_fill(void);

#endif // GFX_GFX_VFX_H
