#!/usr/bin/env node
// port/foh/face-lint.js — THE FACE-DOMAIN LINT (spec #20, ticket #24).
//
// WHAT THIS IS, AND WHY IT IS THE THIRD LAYER
// -------------------------------------------
// A string is only DRAWABLE if every character in it is in the face (see
// CONTEXT.md, "Face domain"). There are three defences against a string that
// is not, and they are deliberately different in kind:
//
//   1. #21's rendering check — the witness RENDERS every frame it simulates,
//      so any string a test actually reaches is drawn and judged.
//   2. #21's runtime split — a miss is a gfx_fatal in a check build and a
//      visible placeholder box in the product build.
//   3. THIS LINT — the NAME TABLES. Tool names, wall types, damage types,
//      pause rows, character names, the credits: data that reaches the
//      renderer with no call site of its own. Layer 1 only sees such an
//      entry if a test happens to draw that exact row, and a test would have
//      to visit all ten tool names and all four damage types to see them all.
//      This layer reads the tables instead of waiting to be shown one.
//
// THE DOMAIN IS READ, NEVER RESTATED. This script does not contain a list of
// drawable characters. It refuses to run without a probe dump produced by
// port/foh/face_lint_probe.c, which asks foh_font.c itself through
// `foh_face_domain`. Restating a constant instead of reading it is how four
// separate device checks went stale in one week in this project.
//
// TWO FACES, AND THE HOLE THAT MUST STAY. foh_font.c carries kGlyphs (5x7)
// and kGlyphs2 (6x9). Their domains differ by exactly ONE glyph — face 1 has
// no '?' — and that hole is load-bearing: check-foh-flows.sh's finish-banner
// tooth proves the loud missing-glyph failure by drawing "COMPLETE?" through
// face 1. So every drawn table here declares WHICH FACE its draw site uses,
// and a face-1 failure is never to be fixed by adding the character to face
// 1. See this file's fail() text and foh_font.c's note.
//
// ===========================================================================
// WHAT THIS LINT DOES NOT COVER  (read this before trusting it)
// ===========================================================================
// It is a SOURCE SCAN plus a small runtime probe. It is a net UNDER layers 1
// and 2, never a replacement for them, because:
//
//   (a) IT CANNOT SEE THROUGH STRING ASSEMBLY. Several drawn strings are
//       built at draw time from a table lookup plus a number — the target
//       builder's HUD is literally
//         snprintf(line, ..., "%s%s%s   GRID %d", tool, ...)
//       (foh_render.c). This lint checks `tool` (kToolNames) and the format's
//       own literal characters are checked only where they are passed
//       directly to foh_text/foh_text2; it cannot check what %d or %s
//       produce. Layer 1 draws the assembled string; layer 2 survives it.
//   (b) IT ONLY SEES TABLES. A one-off literal handed to a helper wrapper
//       (text_in, text_center, text2_center, header, tb_msg) is not a table
//       and is not scanned; only literals passed DIRECTLY to foh_text or
//       foh_text2 are. Refusal strings set through a message setter are in
//       that gap, and layer 1 is what covers them.
//   (c) IT CANNOT EXPAND MACROS. A table generated by an X-macro (e.g.
//       foh_pause.c's drain_held_names) contains no literal for the scanner
//       to find. That one is a stderr diagnostic, not a drawn string, but a
//       DRAWN X-macro table would be invisible here.
//   (d) IT IS STATIC. A string that arrives from outside the tree — a file,
//       an argv, a share code — has no literal anywhere. Those are validated
//       where they are read (foh_tbuild.c's grammar), not here.
//
// ===========================================================================
// Usage:
//   node port/foh/face-lint.js --probe <probe-dump> [--overlay <dir>]
//
// --overlay lets a tooth point the scan at a PERTURBED COPY of one file
// without writing the committed tree: every census path is read from
// <dir>/<path> when that exists and from the repo otherwise.
//
// Exit 0 and `FACE LINT PASS` on success; nonzero with a named entry on any
// failure. `bash port/foh/check-face-lint.sh` is the runnable check.

'use strict';

const fs = require('fs');
const path = require('path');
const cp = require('child_process');

// --- args -------------------------------------------------------------------
let probePath = null;
let overlay = null;
for (let i = 2; i < process.argv.length; i++) {
  const a = process.argv[i];
  if (a === '--probe') probePath = process.argv[++i];
  else if (a === '--overlay') overlay = process.argv[++i];
  else die(`unknown argument |${a}|`);
}
if (!probePath) die('--probe <file> is required: the domain is READ from the ' +
  'font (port/foh/face_lint_probe.c), never restated here');

let failures = 0;
function die(msg) {
  console.error('FACE LINT FAIL: ' + msg);
  process.exit(2);
}
function bad(msg) {
  console.error('FACE LINT FAIL: ' + msg);
  failures++;
}

// --- [1] the domain, read out of foh_font.c ---------------------------------
// The probe dump's grammar is strict and its END marker is required, so a
// truncated or half-written dump can never be mistaken for a small domain.
const probeRaw = fs.readFileSync(probePath, 'utf8');
const probeLines = probeRaw.split('\n');
if (!probeLines.includes('END')) {
  die(`the probe dump ${probePath} has no END marker — it is truncated, and a ` +
    'truncated domain would silently pass everything');
}
const domain = { face1: null, face2: null };
const runtimeRows = [];
for (const ln of probeLines) {
  if (ln === '' || ln === 'END') continue;
  let m = /^DOMAIN ([12]) (\d+)((?: [0-9a-f]{2})+)$/.exec(ln);
  if (m) {
    const chars = m[3].trim().split(' ').map((h) => String.fromCharCode(parseInt(h, 16)));
    if (chars.length !== Number(m[2])) {
      die(`DOMAIN ${m[1]}: the probe declared ${m[2]} glyphs and listed ${chars.length}`);
    }
    domain['face' + m[1]] = new Set(chars);
    continue;
  }
  m = /^RUNTIME (\S+) (\S+) (face1|face2) (raw|upper) (\d+) (.*)$/.exec(ln);
  if (m) {
    runtimeRows.push({
      file: m[1], sym: m[2], face: m[3], xform: m[4],
      idx: Number(m[5]), text: m[6], line: 0,
    });
    continue;
  }
  die(`the probe dump has a line the grammar does not allow: |${ln}|`);
}
if (!domain.face1 || !domain.face2) {
  die('the probe dump is missing a DOMAIN line — both faces must be read');
}
// Face 1 is the SAFE domain only while it is a subset of face 2. Measured,
// never assumed: if a glyph ever exists in face 1 alone, `both` must stop
// meaning "face 1" and this says so instead of quietly narrowing.
const onlyIn1 = [...domain.face1].filter((c) => !domain.face2.has(c));
const both = new Set([...domain.face1].filter((c) => domain.face2.has(c)));
const domainFor = (face) => (face === 'face2' ? domain.face2
  : face === 'face1' ? domain.face1 : both);

// --- [2] the registry -------------------------------------------------------
// EVERY string-bearing table the census finds must appear here, and every row
// here must still be found by the census. Both directions are enforced: an
// unregistered table fails (a new name table cannot arrive unchecked) and a
// registry row with no table fails (this list cannot rot into fiction).
//
//   draw: 'face1' | 'face2' — the table reaches the renderer; the face is the
//         one its DRAW SITE uses, cited in `why`.
//   draw: 'both'           — drawn through both faces; checked against the
//                            intersection.
//   draw: false            — never drawn. `why` says what the strings ARE.
//   xform: 'upper'         — the renderer uppercases at the draw site, so the
//                            lint checks the uppercased form (foh_upper;
//                            pinned textually by check-face-lint.sh).
//   nth                    — 0 unless a file holds two tables of one name.
const REGISTRY = [
  // ---- DRAWN -------------------------------------------------------------
  { file: 'port/foh/foh.c', sym: 'foh_credits', draw: 'face1', xform: 'upper',
    why: 'the fourteen credits; render_credits draws name/role/blurb through ' +
         'foh_text after foh_upper (foh_render.c:2222-2270)' },
  { file: 'port/foh/foh_render.c', sym: 'kMenuTitle', draw: 'face2',
    why: 'the mode title, foh_text2 italic (foh_render.c:1080)' },
  { file: 'port/foh/foh_render.c', sym: 'kMenuText', draw: 'face2',
    why: 'the menu bar labels, foh_text2 (foh_render.c:1102,1115)' },
  { file: 'port/foh/foh_render.c', sym: 'kMenuExpl', draw: 'face2',
    why: 'the explanation bar, foh_text2 (foh_render.c:1153-1155). NOTE it ' +
         'carries "WHO DID THIS?" — a face-2 draw site is exactly why the ' +
         'face is declared per table instead of everything being held to face 1' },
  { file: 'port/foh/foh_render.c', sym: 'kStageNames', draw: 'face2',
    why: 'the SSS stage name, foh_text2 (foh_render.c:1814,1820)' },
  { file: 'port/foh/foh_render.c', sym: 'kCharNames', draw: 'face1',
    why: 'the target-select launch panel, text_in -> foh_text (:2552)' },
  { file: 'port/foh/foh_render.c', sym: 'kCharShort', draw: 'face1',
    why: 'the CSS cell + port name-plates, text_in -> foh_text (:1489,1594,2505)' },
  { file: 'port/foh/foh_render.c', sym: 'kStageShort', draw: 'face1',
    why: 'the SSS thumb strips, text_in -> foh_text (:1831)' },
  { file: 'port/foh/foh_render.c', sym: 'kLCancelNames', draw: 'face1',
    why: 'the gameplay L-CANCEL value cell, foh_text (:1869,1877)' },
  { file: 'port/foh/foh_render.c', sym: 'kRows', draw: 'face1',
    why: 'the gameplay option row labels, row_label -> foh_text (:1874)' },
  { file: 'port/foh/foh_render.c', sym: 'kRow', draw: 'face1',
    why: 'the audio option row labels, row_label -> foh_text (:1935)' },
  { file: 'port/foh/foh_render.c', sym: 'kBtn', draw: 'face1',
    why: 'the Controls screen button column, foh_text (render_ctrl_key)' },
  { file: 'port/foh/foh_render.c', sym: 'kTbPause', draw: 'face1',
    why: 'the target-builder pause rows, text_center -> foh_text (:2832)' },
  { file: 'port/foh/foh_pause.c', sym: 'kSysOptName', draw: 'face2',
    why: 'the system pause menu row, text2_center -> foh_text2 (:606)' },
  { file: 'port/foh/foh_tbuild.c', sym: 'kToolNames', draw: 'face1',
    why: 'the builder HUD tool name; reaches foh_render.c:2788 through the ' +
         'view and is snprintf-assembled there (see the NOT COVERED note)' },
  { file: 'port/foh/foh_tbuild.c', sym: 'kWallTypeNames', draw: 'face1',
    why: 'the builder HUD type name for the WALL tool (view -> :2791)' },
  { file: 'port/foh/foh_tbuild.c', sym: 'kDamageTypeNames', draw: 'face1',
    why: 'the builder HUD type name for the DAMAGE tool (view -> :2791)' },

  // ---- NOT DRAWN ---------------------------------------------------------
  { file: 'port/foh/foh.c', sym: 'kCssAnnouncer', draw: false,
    why: 'announcer SFX names (the sound namespace, CONTEXT.md)' },
  { file: 'port/foh/foh.c', sym: 'kCssCharField', draw: false,
    why: 'foh_persist record field names (the settings file grammar)' },
  { file: 'port/foh/foh.c', sym: 'kCssTypeField', draw: false,
    why: 'foh_persist record field names' },
  { file: 'port/foh/foh.c', sym: 'kCssDiffField', draw: false,
    why: 'foh_persist record field names' },
  { file: 'port/foh/foh_dev.c', sym: 'kMusTok', draw: false,
    why: 'music track tokens handed to the mixer, never painted' },
  { file: 'port/foh/foh_render.c', sym: 'kCharArt', draw: false,
    why: 'IMG1 asset directory names (pipeline `assets` stage)' },
  { file: 'port/foh/foh_render.c', sym: 'kStageArt', draw: false,
    why: 'IMG1 asset directory names' },
  { file: 'port/foh/foh_render.c', sym: 'cand', draw: false,
    why: 'menu.img1 filesystem search paths' },
  { file: 'port/foh/foh_render.c', sym: 'kHand', draw: false,
    why: 'IMG1 sprite names handed to art()/blit_img' },
  { file: 'port/foh/foh_tbuild.c', sym: 'kDamageTypeValues', draw: false,
    why: 'the SHARE-CODE values upstream writes ({damageType:"fire"}); they ' +
         'go into a .mlstage, never onto the screen — the drawn form is ' +
         'kDamageTypeNames above' },
  { file: 'port/foh/foh_controls_witness.c', sym: 'kAll', draw: false,
    why: 'a witness EXPECTATION list measured for width; the drawn source is ' +
         'kMenuExpl, which is checked' },
  { file: 'port/foh/foh_cssbacksel_witness.c', sym: 'kName', draw: false,
    why: 'witness expectation: persist/asset character tokens' },
  { file: 'port/foh/foh_cssrest_witness.c', sym: 'kName', draw: false,
    why: 'witness expectation: persist/asset character tokens' },
  { file: 'port/foh/foh_launch_witness.c', sym: 'kVerdicts', draw: false,
    why: 'witness expectation: per-frame L/R verdict letters' },
  { file: 'port/foh/foh_p34_witness.c', sym: 'kCharName', draw: false,
    why: 'witness expectation: persist/asset character tokens' },
  { file: 'port/foh/foh_p34_witness.c', sym: 'kTypeField', draw: false,
    why: 'witness expectation: foh_persist field names' },
  { file: 'port/foh/foh_p34_witness.c', sym: 'kPostV5', draw: false,
    why: 'witness expectation: the post-v5 persist row prefixes it strips' },
  { file: 'port/foh/foh_rebind_witness.c', sym: 'kBtn', draw: false,
    why: 'witness expectation: a hand copy of foh_render.c kBtn, which is the ' +
         'drawn table and IS checked' },
  { file: 'port/foh/foh_rebind_witness.c', sym: 'kCssRows', draw: false,
    why: 'witness expectation: persist row prefixes' },
  { file: 'port/foh/foh_snd_witness.c', sym: 'kCases', draw: false,
    why: 'witness expectation: sound-event names' },
  { file: 'port/foh/foh_snd_witness.c', sym: 'pins', draw: false,
    why: 'witness expectation: sound-event names' },
  { file: 'port/gfx/gfx_render.c', sym: 'names', nth: 0, draw: false,
    why: 'ANIM1 per-character directory names (gfx_load_anim)' },
  { file: 'port/gfx/gfx_render.c', sym: 'names', nth: 1, draw: false,
    why: 'the render profiler`s stage labels, fprintf to stderr' },
  { file: 'port/gfx/gfx_vfx.c', sym: 'v_names', draw: false,
    why: 'vfx template names (the vfx namespace, CONTEXT.md)' },
  { file: 'port/gfx/platform_keymap.h', sym: 'kPlatformKeymap', draw: false,
    why: 'SDL keysym names for the input path' },
  { file: 'port/gfx/platform_sdl1.c', sym: 'kSonames', draw: false,
    why: 'dlopen() soname candidates' },
  { file: 'port/gfx/s1_input.h', sym: 'T', nth: 0, draw: false,
    why: 'S1 chord row diagnostic names (BOX table)' },
  { file: 'port/gfx/s1_input.h', sym: 'T', nth: 1, draw: false,
    why: 'S1 chord row diagnostic names (NORMAL table)' },
  { file: 'port/gfx/s1_input.h', sym: 'T', nth: 2, draw: false,
    why: 'S1 chord row diagnostic names (NATURAL table)' },
  { file: 'port/gfx/snd_playid_check.c', sym: 'ents', draw: false,
    why: 'sound names in a play-id probe' },
];

// --- [3] the census ---------------------------------------------------------
// Scope: every committed C source and header under the three trees that can
// reach the font (port/foh, port/gfx, port/sim/target — measured: the only
// callers of foh_text/foh_text2 live in port/foh and port/gfx/gfx_target.c).
const CENSUS_GLOBS = [
  'port/foh/*.c', 'port/foh/*.h',
  'port/gfx/*.c', 'port/gfx/*.h',
  'port/sim/target/*.c', 'port/sim/target/*.h',
];
const files = cp
  .execSync('git ls-files -- ' + CENSUS_GLOBS.map((g) => `'${g}'`).join(' '),
            { encoding: 'utf8' })
  .trim().split('\n').filter(Boolean);
if (files.length < 40) die(`the census listed only ${files.length} files — ` +
  'run this from the repository root');

function readSource(rel) {
  if (overlay) {
    const o = path.join(overlay, rel);
    if (fs.existsSync(o)) return { text: fs.readFileSync(o, 'utf8'), from: o };
  }
  return { text: fs.readFileSync(rel, 'utf8'), from: rel };
}

// Comments out, string literals kept byte-for-byte (a `"` inside a comment
// must not open a literal, and a `//` inside a literal must not open a
// comment — both happen in this tree).
function stripComments(src) {
  let out = '', i = 0;
  const n = src.length;
  while (i < n) {
    const c = src[i];
    if (c === '"' || c === "'") {
      let j = i + 1;
      while (j < n) {
        if (src[j] === '\\') { j += 2; continue; }
        if (src[j] === c) { j++; break; }
        j++;
      }
      out += src.slice(i, j); i = j; continue;
    }
    if (c === '/' && src[i + 1] === '/') {
      let j = src.indexOf('\n', i);
      if (j < 0) j = n;
      i = j; continue;
    }
    if (c === '/' && src[i + 1] === '*') {
      let j = src.indexOf('*/', i + 2);
      j = j < 0 ? n : j + 2;
      out += ' '; i = j; continue;
    }
    out += c; i++;
  }
  return out;
}

// Skip forward over a balanced region, treating string literals as opaque.
function matchBrace(s, from, open, close) {
  let d = 1, i = from;
  while (i < s.length && d > 0) {
    const c = s[i];
    if (c === '"') {
      let j = i + 1;
      while (j < s.length) {
        if (s[j] === '\\') { j += 2; continue; }
        if (s[j] === '"') { j++; break; }
        j++;
      }
      i = j; continue;
    }
    if (c === open) d++;
    else if (c === close) d--;
    i++;
  }
  return i - 1; // index of the closing delimiter
}

function unescapeC(lit) {
  return lit.replace(/\\(x[0-9a-fA-F]{1,2}|[0-7]{1,3}|.)/g, (m, e) => {
    if (e[0] === 'x') return String.fromCharCode(parseInt(e.slice(1), 16));
    if (/^[0-7]+$/.test(e)) return String.fromCharCode(parseInt(e, 8));
    const map = { n: '\n', t: '\t', r: '\r', '0': '\0', '\\': '\\', '"': '"', "'": "'" };
    return Object.prototype.hasOwnProperty.call(map, e) ? map[e] : e;
  });
}

function literalsIn(body) {
  return [...body.matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((m) => unescapeC(m[1]));
}

const lineOf = (s, idx) => s.slice(0, idx).split('\n').length;

// Any array initializer that carries at least one string literal. This is
// wider than `const char *x[]` on purpose: the credits table is an array of
// STRUCTS whose members are drawn, and the first draft of this scan missed it.
const TABLE_RE = /\b(\w+)\s*((?:\[[^\]]*\]\s*)+)=\s*\{/g;
// Literals handed DIRECTLY to a font entry point. The face is the callee's,
// so these need no registry row (see NOT COVERED (b) for what this misses).
const CALL_RE = /\bfoh_text(2?)\s*\(/g;

const found = [];       // census rows
const directCalls = []; // literal-at-a-draw-site rows
for (const rel of files) {
  const { text } = readSource(rel);
  const s = stripComments(text);
  TABLE_RE.lastIndex = 0;
  const seenSym = new Map();
  let m;
  while ((m = TABLE_RE.exec(s))) {
    const close = matchBrace(s, TABLE_RE.lastIndex, '{', '}');
    const body = s.slice(TABLE_RE.lastIndex, close);
    const lits = literalsIn(body);
    if (lits.length === 0) continue;
    const sym = m[1];
    const nth = seenSym.get(sym) || 0;
    seenSym.set(sym, nth + 1);
    found.push({ file: rel, sym, nth, line: lineOf(s, m.index), lits });
  }
  CALL_RE.lastIndex = 0;
  while ((m = CALL_RE.exec(s))) {
    const close = matchBrace(s, CALL_RE.lastIndex, '(', ')');
    const args = s.slice(CALL_RE.lastIndex, close);
    for (const lit of literalsIn(args)) {
      directCalls.push({
        file: rel, sym: 'foh_text' + (m[1] || '') + '() literal',
        face: m[1] === '2' ? 'face2' : 'face1',
        line: lineOf(s, m.index), text: lit,
      });
    }
  }
}

// --- [4] census vs registry, both directions --------------------------------
const key = (r) => `${r.file}::${r.sym}#${r.nth || 0}`;
const regByKey = new Map();
for (const r of REGISTRY) {
  const k = key(r);
  if (regByKey.has(k)) die(`the registry has two rows for ${k}`);
  regByKey.set(k, r);
}
const seenKeys = new Set();
for (const t of found) {
  const k = key(t);
  seenKeys.add(k);
  if (!regByKey.has(k)) {
    bad(`${t.file}:${t.line} ${t.sym} is a table of ${t.lits.length} string(s) ` +
      `that this lint has never been told about.\n` +
      `  Add a row to REGISTRY in port/foh/face-lint.js saying whether it ` +
      `reaches the renderer:\n` +
      `    draw: 'face1' | 'face2'  — with the DRAW SITE cited in \`why\`\n` +
      `    draw: false              — with what the strings actually ARE\n` +
      `  A new name table must not arrive unchecked; that is the whole point ` +
      `of this leg.`);
  }
}
for (const r of REGISTRY) {
  if (!seenKeys.has(key(r))) {
    bad(`the registry claims ${key(r)} exists and the census cannot find it. ` +
      `Either the table was renamed or removed (update port/foh/face-lint.js ` +
      `in the same change) or the scanner stopped recognising its shape — and ` +
      `a registry that describes tables which are not there is exactly how a ` +
      `check goes quietly vacuous.`);
  }
}

// --- [5] the judgment -------------------------------------------------------
function faceLabel(face) {
  return face === 'both' ? 'face1 & face2 (intersection)' : face;
}
function checkString(where, face, raw, xform) {
  const text = xform === 'upper' ? raw.toUpperCase() : raw;
  const dom = domainFor(face);
  for (const ch of text) {
    if (dom.has(ch)) continue;
    const hex = ch.charCodeAt(0).toString(16).padStart(2, '0');
    const shown = ch === '\n' ? '\\n' : ch === '\t' ? '\\t' : ch;
    bad(`${where}\n` +
      `  string  : "${raw}"${xform === 'upper' ? ` (drawn as "${text}")` : ''}\n` +
      `  offender: '${shown}' (0x${hex}) is not in ${faceLabel(face)}\n` +
      `  This string cannot be drawn: it is a gfx_fatal in a check build and a ` +
      `placeholder box for the player.\n` +
      `  FIX THE STRING, or — if this entry is really drawn in the other face — ` +
      `fix the face this table declares in port/foh/face-lint.js and cite the ` +
      `draw site.\n` +
      `  DO NOT widen face 1 to make this pass: face 1's missing '?' is held ` +
      `hostage by check-foh-flows.sh's finish-banner tooth (foh_font.c's note).`);
    return;
  }
}

let checkedTables = 0, checkedStrings = 0;
for (const t of found) {
  const r = regByKey.get(key(t));
  if (!r || !r.draw) continue;
  checkedTables++;
  t.lits.forEach((lit, i) => {
    checkedStrings++;
    checkString(`${t.file}:${t.line} ${t.sym}[${i}]`, r.draw, lit, r.xform);
  });
}
for (const r of runtimeRows) {
  checkedStrings++;
  checkString(`${r.file} ${r.sym}[${r.idx}] (runtime, from the probe)`,
              r.face, r.text, r.xform);
}
for (const c of directCalls) {
  checkedStrings++;
  checkString(`${c.file}:${c.line} ${c.sym}`, c.face, c.text, 'raw');
}

// --- [6] the verdict --------------------------------------------------------
if (failures) {
  console.error(`FACE LINT: ${failures} failure(s)`);
  process.exit(1);
}
console.log(`  domain read from foh_font.c: face1=${domain.face1.size} glyphs, ` +
  `face2=${domain.face2.size} glyphs, intersection=${both.size}` +
  (onlyIn1.length ? `, face1-only=${JSON.stringify(onlyIn1)}` : ''));
console.log(`  census: ${found.length} string-bearing tables in ${files.length} ` +
  `committed sources; all ${REGISTRY.length} registered, ${checkedTables} drawn`);
console.log(`  checked: ${checkedStrings} strings ` +
  `(${runtimeRows.length} runtime-enumerated, ${directCalls.length} literals at ` +
  `foh_text/foh_text2 call sites)`);
console.log('  NOT COVERED (this is a net under the runtime check, not a ' +
  'replacement): snprintf-assembled strings, literals passed to helper ' +
  'wrappers or message setters, X-macro tables, and anything read from a file ' +
  'at runtime. See this file`s header.');
console.log('FACE LINT PASS');
